# Generated by Django 4.0.1 on 2022-04-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school1', models.TextField(max_length=50, null=True)),
                ('board1', models.TextField(max_length=50)),
                ('marks1', models.TextField(max_length=50)),
                ('total1', models.IntegerField()),
                ('percentage1', models.IntegerField()),
                ('dop1', models.DateField()),
                ('file1', models.FileField(upload_to='')),
                ('school2', models.TextField(max_length=50)),
                ('board2', models.TextField(max_length=50)),
                ('marks2', models.TextField(max_length=50)),
                ('total2', models.IntegerField()),
                ('percentage2', models.IntegerField()),
                ('dop2', models.DateField()),
                ('file2', models.FileField(upload_to='')),
                ('school3', models.TextField(max_length=50)),
                ('board3', models.TextField(max_length=50)),
                ('marks3', models.TextField(max_length=50)),
                ('total3', models.IntegerField()),
                ('percentage3', models.IntegerField()),
                ('dop3', models.DateField()),
                ('file3', models.FileField(upload_to='')),
                ('school4', models.TextField(max_length=50)),
                ('board4', models.TextField(max_length=50)),
                ('marks4', models.TextField(max_length=50)),
                ('total4', models.IntegerField()),
                ('percentage4', models.IntegerField()),
                ('dop4', models.DateField()),
                ('file4', models.FileField(upload_to='')),
            ],
        ),
    ]
