# Generated by Django 4.0.1 on 2022-04-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_qualification_file1_alter_qualification_file2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='signuptab',
        ),
    ]
