# Generated by Django 4.0.1 on 2022-04-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_signin_signintab'),
    ]

    operations = [
        migrations.CreateModel(
            name='createprofiletab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(max_length=50)),
                ('lname', models.TextField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('ccode', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.TextField(max_length=50)),
                ('secemail', models.TextField(max_length=50)),
                ('add', models.TextField(max_length=151)),
                ('city', models.TextField(max_length=20)),
                ('pin', models.IntegerField(max_length=6)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('hobbies', models.TextField(max_length=50)),
            ],
        ),
    ]
