# Generated by Django 4.0.1 on 2022-04-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_createprofiletab_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='createprofiletab',
            name='user_id',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
