# Generated by Django 4.0.1 on 2022-04-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_createprofiletab_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createprofiletab',
            name='pin',
            field=models.IntegerField(null=True),
        ),
    ]
