# Generated by Django 4.0.1 on 2022-04-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_createprofiletab_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='qualificationtab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree1', models.CharField(max_length=10)),
                ('school1', models.TextField(max_length=50, null=True)),
                ('board1', models.TextField(max_length=50)),
                ('aos', models.TextField(max_length=20)),
                ('country1', models.TextField(max_length=20)),
                ('state1', models.TextField(max_length=20)),
                ('percentage1', models.IntegerField()),
                ('dop1', models.DateField()),
                ('file1', models.FileField(upload_to='GFG/gfg/UploadDoc')),
            ],
        ),
        migrations.DeleteModel(
            name='qualification',
        ),
    ]
