# Generated by Django 4.0.1 on 2022-04-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_qualificationtab_aos_qualificationtab_aos1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='qualificationtab1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(max_length=10)),
                ('degreedetail2', models.TextField(max_length=20)),
                ('degree2', models.CharField(max_length=10)),
                ('school2', models.TextField(max_length=50)),
                ('board2', models.TextField(max_length=50)),
                ('aos2', models.TextField(max_length=20)),
                ('country2', models.TextField(max_length=20)),
                ('state2', models.TextField(max_length=20)),
                ('percentage2', models.IntegerField()),
                ('dop2', models.DateField()),
                ('file2', models.FileField(upload_to='GFG/gfg/UploadDoc')),
            ],
        ),
    ]
