# Generated by Django 4.0.1 on 2022-04-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_qualificationtab2'),
    ]

    operations = [
        migrations.CreateModel(
            name='qualificationtab3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(max_length=10)),
                ('degreedetail4', models.TextField(max_length=20)),
                ('degree4', models.CharField(max_length=10)),
                ('institute4', models.TextField(max_length=50)),
                ('university4', models.TextField(max_length=50)),
                ('aos4', models.TextField(max_length=20)),
                ('country4', models.TextField(max_length=20)),
                ('state4', models.TextField(max_length=20)),
                ('percentage4', models.IntegerField()),
                ('dop4', models.DateField()),
                ('file4', models.FileField(upload_to='GFG/gfg/UploadDoc')),
            ],
        ),
    ]
