# Generated by Django 4.0.1 on 2022-04-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_patentstab'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificatetab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(max_length=10)),
                ('certificate_no', models.TextField(max_length=50)),
                ('certified_by', models.TextField(max_length=100)),
                ('certificate_reg_no', models.TextField(max_length=50)),
                ('certificate_coursename', models.TextField(max_length=50)),
                ('certificate_courseduration', models.TextField(max_length=50)),
                ('certificate_gradeachieved', models.TextField(max_length=50)),
                ('certificate_dateofissue', models.DateField()),
                ('certificate_validtill', models.DateField()),
                ('certificate_uploadcertificate', models.FileField(upload_to='GFG/gfg/UploadDoc')),
            ],
        ),
    ]
