# Generated by Django 4.0.1 on 2022-05-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_certificatetab'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievementstab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(max_length=10)),
                ('achievements_title', models.TextField(max_length=50)),
                ('achievements_details', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='projecttab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(max_length=10)),
                ('project_name', models.TextField(max_length=50)),
                ('project_details', models.TextField(max_length=50)),
                ('project_role', models.TextField(max_length=50)),
                ('project_duration', models.TextField(max_length=50)),
                ('team_size', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='skilltab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(max_length=10)),
                ('skill_title', models.TextField(max_length=50)),
                ('skill_details', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='workexperiencetab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(max_length=10)),
                ('work_organization', models.TextField(max_length=50)),
                ('work_designation', models.TextField(max_length=50)),
                ('work_from', models.DateField()),
                ('work_to', models.DateField()),
                ('work_responsibility', models.TextField(max_length=50)),
            ],
        ),
    ]
