# Generated by Django 4.0.1 on 2022-05-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_achievementstab_projecttab_skilltab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttab',
            name='fund_document',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projecttab',
            name='giturl',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projecttab',
            name='projectfund',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projecttab',
            name='projectwebsite',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workexperiencetab',
            name='attach_experience',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
