# Generated by Django 4.0.1 on 2022-05-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_projecttab_fund_document_projecttab_giturl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementstab',
            name='achievements_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='achievementstab',
            name='achievements_proof',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='achievementstab',
            name='award',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
